/*************************************************
 * Wallet
 * @exports
 * SharedImages.ts
 * Created by Dhivya on 27/07/2023
 * Copyright © 2023 Wallet. All rights reserved.
 *************************************************/

// logos, images and icons
export const IMAGES = {
  background_image: require('../assets/images/bg-image.png'),
  logo: require('../assets/images/logo.png'),
  letsgo: require('../assets/images/letsgo.png'),
  login_bg: require('../assets/images/loginbg.png'),
  informationIcon: require('../assets/images/information.png'),
  eyeopen: require('../assets/images/eyeopen.png'),
  eyecross: require('../assets/images/eyecross.png'),
  backgroundImg: require('../assets/images/backgroundimg.png'),
  homeInActive: require('../assets/images/home.png'),
  bankInActive: require('../assets/images/bank.png'),
  profileInActive: require('../assets/images/profile.png'),
  homeActive: require('../assets/images/homeActive.png'),
  bankActive: require('../assets/images/bankActive.png'),
  profileActive: require('../assets/images/profileactive.png'),
  bellIcon: require('../assets/images/bell.png'),
  transfer: require('../assets/images/transfer.png'),
  fund: require('../assets/images/fund.png'),
  withdraw: require('../assets/images/withdraw.png'),
  menu: require('../assets/images/menu.png'),
  tickRounded: require('../assets/images/tick.png'),
  transactionTick: require('../assets/images/tickrounded.png'),
  warning: require('../assets/images/warning.png'),
  crossIcon: require('../assets/images/cross.png'),
  threeDot: require('../assets/images/threedotrounded.png'),
  downArrow: require('../assets/images/downarrow.png'),
  downArrowBlue: require('../assets/images/downarrowblue.png'),
  bankLogo1: require('../assets/images/banklogo1.png'),
  bankLogo2: require('../assets/images/banklogo2.png'),
  bankLogo3: require('../assets/images/banklogo3.png'),
  bankLogo4: require('../assets/images/banklogo4.png'),
  bankLogo5: require('../assets/images/banklogo5.png'),
  bankLogo6: require('../assets/images/banklogo6.png'),
  bankLogo7: require('../assets/images/banklogo7.png'),
  bankLogo8: require('../assets/images/banklogo8.png'),
  addBank: require('../assets/images/addbank.png'),
  bankImageGreen: require('../assets/images/bankimagegreen.png'),
  plus: require('../assets/images/plus.png'),
  rightArrow: require('../assets/images/rightarrow.png'),
  rightArrowBlue: require('../assets/images/rightarrowblue.png'),
  closeIcon: require('../assets/images/close.png'),
  backArrow: require('../assets/images/backarrow.png'),
  searchIcon: require('../assets/images/searchicon.png'),
  searchIconRight: require('../assets/images/searchright.png'),
  profile1: require('../assets/images/profile1.png'),
  profile2: require('../assets/images/profile2.png'),
  profile3: require('../assets/images/profile3.png'),
  profile4: require('../assets/images/profile4.png'),
  profile5: require('../assets/images/profile5.png'),
  radioButtonClicked: require('../assets/images/radioClick.png'),
  radioButtonUnClicked: require('../assets/images/radiounclick.png'),
  bankAccount: require('../assets/images/bankaccount.png'),
  transactionhistory: require('../assets/images/transaction.png'),
  profileBgImage: require('../assets/images/profilebgimage.png'),
  profilepictures: require('../assets/images/profilepic.png'),
  changePwd: require('../assets/images/changepwd.png'),
  contactUs: require('../assets/images/contactus.png'),
  delete: require('../assets/images/delete.png'),
  edit: require('../assets/images/edit.png'),
  logout: require('../assets/images/logout.png'),
  notification: require('../assets/images/notification.png'),
  settings: require('../assets/images/setting.png'),
  termsAndConditions: require('../assets/images/terms&con.png'),
  plaidsImage: require('../assets/images/plaidsImage.png'),
  connect: require('../assets/images/connect.png'),
  plaidLogo: require('../assets/images/plaidlogo.png'),
  plaidbg: require('../assets/images/plaidbg.png'),
  fpb: require('../assets/images/fpb.png'),
  whiteTick: require('../assets/images/whitetick.png'),
  checkBox: require('../assets/images/checkbox.png'),
  plaidsuccess: require('../assets/images/plaidsuccess.png'),
  modalCheckBox: require('../assets/images/modalcheckbox.png'),
  dataArrow: require('../assets/images/dataarrow.png'),
};
